version: 2

rspec: &rspec
  steps:
    - checkout
    - run: bundle install
    - run: rake spec

jobs:
  # Ruby 2.3
  ruby-2.3-rspec:
    docker:
      - image: circleci/ruby:2.3
    <<: *rspec

  # Ruby 2.4
  ruby-2.4-rspec:
    docker:
      - image: circleci/ruby:2.4
    <<: *rspec

  # Ruby 2.5
  ruby-2.5-rspec:
    docker:
      - image: circleci/ruby:2.5
    <<: *rspec

  # JRuby
  jruby:
    docker:
      - image: circleci/jruby:9
    steps:
      - checkout
      - run: sudo apt-get install -y make
      - run: bundle lock
      - restore_cache:
          keys:
            - bundle-v2-{{ checksum "Gemfile.lock" }}
            - bundle-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: rake spec

  code-climate:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run specs
          command: |
            ./cc-test-reporter before-build
            rake coverage
            ./cc-test-reporter after-build --exit-code $?

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.3-rspec
      - ruby-2.4-rspec
      - ruby-2.5-rspec
      - jruby
      - code-climate
